config/routes.rb
Rails.application.routes.draw do
  resources :feeds
  resources :contacts
  # get 'sessions/new'
  # get 'blogs/index'
  resources :blogs do
    collection do
      post :confirm
    end
  end

  resources :sessions, only: [:new, :create, :destroy]
  resources :users, only: [:new, :create, :show, :edit, :update]
  resources :favorites, only: [:index, :create, :destroy]

  mount LetterOpenerWeb::Engine, at: "/letter_opener" if Rails.env.development?

  resources :feeds do
    collection do
      post :confirm
    end
  end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/blog.rb
class Blog < ApplicationRecord
  belongs_to :user
  has_many :favorites, dependent: :destroy
  has_many :favorite_users, through: :favorites, source: :user

  validates :title, presence: true

  # mount_uploader :photo, ImageUploader
  mount_uploader :image, BlogImageUploader
end

app/controllers/blogs_controller.rb
class BlogsController < ApplicationController
  before_action :set_blog, only: [:show, :edit, :update, :destroy]
  # before_action :logged_in?, only: [:edit, :destroy]

  def index
    @blogs = Blog.all
    
  end

  def new
    @blog = Blog.new
  end

  def create
    # @blog = Blog.create(blog_params)
    # if @blog.save
    # redirect_to blogs_path, notice:"ブログを作成しました。"
    # else 
    # render :new 
    # end

    # back機能を兼ね揃えたcreateの書き方。back時parameterが失われない。
    # @blog = Blog.new(blog_params)
    # @blog.user_id = current_user.id
    # 上記2行は下記1行で完結できる。current_user.blogs.buildは「ログイン中のユーザーの、blogを、build(new)する」
    @blog = current_user.blogs.build(blog_params)
    # binding.irb
    if params[:back]
      render :new
    else
      if @blog.save
        # binding.irb
        NoticeMailer.notice_mailer(@blog).deliver
        # binding.irb
        redirect_to blogs_path, notice: "ブログを作成しました！"
      else
        render :new
      end
    end
  end

  def show
    
  end

  def edit
    if current_user.id != @blog.user_id
      # binding.irb
      redirect_to blogs_path, notice:"他人のブログ編集は出来ません!"
    end
    
  end

  def update
    if @blog.update(blog_params)
      # binding.irb
      redirect_to blogs_path, notice:"ブログを編集しました。"
    else
      render :edit
    end
  end

  def destroy
    if current_user.id != @blog.user_id
      # binding.irb
      redirect_to blogs_path, notice:"他人のブログ削除は出来ません!"
    else
      @blog.destroy
      redirect_to blogs_path, notice:"ブログを削除しました！"
    end
  end

  def confirm
    # @blog = Blog.new(blog_params)
    # @blog.user_id = current_user.id
    @user = User.find(session[:user_id])
    @blog = current_user.blogs.build(blog_params)
    if @blog.invalid?
      render :new
    end
  end


  private
  def blog_params
    params.require(:blog).permit(:title, :content, :image, :image_cache)
  end

  def set_blog
    @blog = Blog.find(params[:id])
  end

  # def logged_in?
  #   unless current_user.present?
  #     redirect_to new_user_path, notice: "ログインするか新規ユーザー設定後Blogをご使用下さい。"
  #   end
  # end
end

app/helpers/blogs_helper.rb
module BlogsHelper
  def choose_new_or_edit
    if action_name == 'new' || action_name == 'create'
      confirm_blogs_path
    elsif action_name == 'edit'
      blog_path
    end
  end
end

app/views/blogs/_form.html.erb
<%# <%= form_with(model: @blog, local: true) do |form| %> %>
<%= form_with(model: @blog, local: true ,url: choose_new_or_edit ) do |form| %>

  <% if @blog.errors.any? %>
    <div id="error_explanation">
      <h2><%= @blog.errors.count %>件のエラーがあります。</h2>
      <ul>
      <% @blog.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  <div class="blog_title">
    <%= form.label :title %>
    <%= form.text_field :title %>
  </div>
  <div class="blog_title">
    <%= form.label :content %>
    <%= form.text_field :content %>
  </div>

  <div class="field">
    <%= form.label :image %>
    <!-- 確認画面から新規作成画面に戻った時に、 -->
    <!-- アップロードした画像を表示させるための記述 -->
    
    <%= form.file_field :image %>
    <%= form.hidden_field :image_cache %>

  <%= form.submit %>
<% end %>
<br>
<%= link_to "ブログ一覧画面にもどる", blogs_path %>

app/views/blogs/confirm.html.erb
<h3>以下の内容で送信する。</h3>
<%= form_with(model: @blog, local: true) do |form| %>
  <%= form.hidden_field :title %>
  <%= form.hidden_field :content %>
  <%= form.hidden_field :image %>
  <%= form.hidden_field :image_cache %>
  <p>タイトル:<%= @blog.title %></p>
  <p>本文:<%= @blog.content %></p>
  <%= form.submit  "登録する" %>
  <%= form.submit "戻る", name: 'back' %>
<% end %>

app/views/blogs/edit.html.erb
<%= form_with(model: @blog, local: true) do |form| %>
  <% if @blog.errors.any? %>
    <div id="error_explanation">
      <h2><%= @blog.errors.count %>件のエラーがあります。</h2>
      <ul>
      <% @blog.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  <div class="blog_title">
    <%= form.label :title %>
    <%= form.text_field :title %>
  </div>
  <div class="blog_content">
    <%= form.label :content %>
    <%= form.text_field :content %>
  </div>

  <div class="field">
    <%= form.label :image %>
    <!-- 確認画面から新規作成画面に戻った時に、 -->
    <!-- アップロードした画像を表示させるための記述 -->
    
    <%= form.file_field :image %>
    <%= form.hidden_field :image_cache %>

  <%= form.submit %>
<% end %>

app/views/blogs/index.html.erb
<h1>ブログ一覧</h1>
<p><%= notice %></p>
<table>
  <tr>
    <th>ユーザーフォト</th>
    <th>ユーザー</th>
    <th>タイトル</th>
    <th>内容</th>
    <th>フォト投稿</th>
  </tr>
<% @blogs.each do |blog| %>
  <tr>
    <td><%= image_tag blog.user.photo.url %></td>
    <td><%= blog.user.name %></td>
    <td><%= blog.title %></td>
    <td><%= blog.content %></td>
    <td><%= image_tag blog.image.to_s %></td>

    <% if logged_in? %>
      <td><%= link_to '詳細確認', blog_path(blog.id) %></td>
        <% if blog.user_id == current_user.id %>
          <td><%= link_to "ブログ編集", edit_blog_path(blog.id), data: { confirm: '本当に編集していいですか？' } %></td>
          <td><%= link_to 'ブログ削除', blog_path(blog.id), method: :delete ,data: { confirm: '本当に削除していいですか？' } %></td>
        <% end %>
    <% else %>
      <td><%= link_to '詳細確認', blog_path(blog.id) %></td>
    <% end %>

  </tr>
<% end %>
</table>
<br>
<%= link_to '新しくブログを投稿する', new_blog_path %>

app/views/blogs/new.html.erb
 <h2>ブログを作成する</h2>
  <%= render 'form' %>

app/views/blogs/show.html.erb
<h1>ブログ詳細画面</h1>
<p>タイトル: <%= @blog.title %></p>
<p>内容: <%= @blog.content %></p>
<p>写真投稿: <%= image_tag(@blog.image.to_s) %></p>
<br>


  <% unless @blog.user_id == current_user.id %>
  <%binding.irb%>
    <% if @favorite.present? %>
    <%binding.irb%>
      <%= link_to 'お気に入り解除する', favorite_path(id: @favorite.id), method: :delete, class: 'btn btn-danger' %>
    <% else %>
      <%= link_to 'お気に入りする', favorites_path(blog_id: @blog.id), method: :post, class: 'btn btn-primary' %>
    <% end %>
    <%binding.irb%>
  <% end %>

<br>
<%= link_to "ブログ一覧画面にもどる", blogs_path %>